import { Anime, Manga, Character, Person, Genre, ReviewItem } from "./types";

export const FALLBACK_GENRES: Genre[] = [
  { mal_id: 1, name: "Action", url: "", count: 4890 },
  { mal_id: 2, name: "Adventure", url: "", count: 3200 },
  { mal_id: 4, name: "Comedy", url: "", count: 6800 },
  { mal_id: 8, name: "Drama", url: "", count: 4900 },
  { mal_id: 10, name: "Fantasy", url: "", count: 5200 },
  { mal_id: 22, name: "Romance", url: "", count: 2900 },
  { mal_id: 24, name: "Sci-Fi", url: "", count: 3100 },
  { mal_id: 30, name: "Sports", url: "", count: 1100 },
  { mal_id: 37, name: "Supernatural", url: "", count: 2100 },
  { mal_id: 41, name: "Suspense", url: "", count: 950 },
];

export const FALLBACK_ANIME: Anime[] = [
  {
    mal_id: 52991,
    url: "https://myanimelist.net/anime/52991/Sousou_no_Frieren",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1015/138075.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1015/138075l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1015/138075.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1015/138075l.webp",
      },
    },
    trailer: {
      youtube_id: "qgQunxD0qMo",
      url: "https://www.youtube.com/watch?v=qgQunxD0qMo",
      embed_url: "https://www.youtube-nocookie.com/embed/qgQunxD0qMo?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    titles: [
      { type: "Default", title: "Sousou no Frieren" },
      { type: "Japanese", title: "葬送のフリーレン" },
      { type: "English", title: "Frieren: Beyond Journey's End" },
    ],
    title: "Sousou no Frieren",
    title_english: "Frieren: Beyond Journey's End",
    title_japanese: "葬送のフリーレン",
    type: "TV",
    source: "Manga",
    episodes: 28,
    status: "Finished Airing",
    airing: false,
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 9.32,
    scored_by: 450000,
    rank: 1,
    popularity: 180,
    members: 890000,
    synopsis: "During their decade-long quest, the hero Himmel, priest Heiter, warrior Eisen, and elven mage Frieren defeated the Demon King, bringing peace to the realm. As an elf whose lifespan exceeds a thousand years, Frieren promises to visit them in 50 years. Decades later, she returns to find her companions aged, and Himmel passes away. Regretting not knowing him better, Frieren embarks on a journey toward the northern lands where souls are said to rest, seeking to understand humans and honor her past companions.",
    season: "fall",
    year: 2023,
    studios: [{ mal_id: 11, name: "Madhouse" }],
    producers: [{ mal_id: 1143, name: "TOHO animation" }, { mal_id: 1468, name: "Crunchyroll" }],
    genres: [
      { mal_id: 2, name: "Adventure" },
      { mal_id: 8, name: "Drama" },
      { mal_id: 10, name: "Fantasy" },
    ],
    themes: [],
    streaming: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/series/GG5H5XMQ5/frieren-beyond-journeys-end" }],
  },
  {
    mal_id: 50709,
    url: "https://myanimelist.net/anime/50709/Cyberpunk__Edgerunners",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1819/126946.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1819/126946l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1819/126946.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1819/126946l.webp",
      },
    },
    trailer: {
      youtube_id: "JtqIas3bYhg",
      url: "https://www.youtube.com/watch?v=JtqIas3bYhg",
      embed_url: "https://www.youtube-nocookie.com/embed/JtqIas3bYhg?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    titles: [
      { type: "Default", title: "Cyberpunk: Edgerunners" },
      { type: "Japanese", title: "サイバーパンク エッジランナーズ" },
      { type: "English", title: "Cyberpunk: Edgerunners" },
    ],
    title: "Cyberpunk: Edgerunners",
    title_english: "Cyberpunk: Edgerunners",
    title_japanese: "サイバーパンク エッジランナーズ",
    type: "ONA",
    source: "Game",
    episodes: 10,
    status: "Finished Airing",
    airing: false,
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.60,
    scored_by: 680000,
    rank: 82,
    popularity: 135,
    members: 950000,
    synopsis: "Dreams are doomed to die in Night City, a Californian metropolis obsessed with cybernetic augmentation and chrome. David Martinez, a disenfranchised youth living with his overworked mother, loses everything in a drive-by tragedy. Destitute and desperate, he implants a military-grade Sandevistan cyberware into his spine, meeting mysterious netrunner Lucy and diving into the high-stakes underworld of Edgerunners.",
    season: "fall",
    year: 2022,
    studios: [{ mal_id: 803, name: "Trigger" }],
    producers: [{ mal_id: 1003, name: "Netflix" }, { mal_id: 2029, name: "CD Projekt Red" }],
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 24, name: "Sci-Fi" },
      { mal_id: 41, name: "Suspense" },
    ],
    themes: [{ mal_id: 50, name: "Cyberpunk" }],
    streaming: [{ name: "Netflix", url: "https://www.netflix.com/title/81054853" }],
  },
  {
    mal_id: 5114,
    url: "https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1208/94745.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1208/94745l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1208/94745.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1208/94745l.webp",
      },
    },
    trailer: {
      youtube_id: "--IcmZkvL0Q",
      url: "https://www.youtube.com/watch?v=--IcmZkvL0Q",
      embed_url: "https://www.youtube-nocookie.com/embed/--IcmZkvL0Q?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    titles: [
      { type: "Default", title: "Fullmetal Alchemist: Brotherhood" },
      { type: "Japanese", title: "鋼の錬金術師 FULLMETAL ALCHEMIST" },
      { type: "English", title: "Fullmetal Alchemist: Brotherhood" },
    ],
    title: "Fullmetal Alchemist: Brotherhood",
    title_english: "Fullmetal Alchemist: Brotherhood",
    title_japanese: "鋼の錬金術師 FULLMETAL ALCHEMIST",
    type: "TV",
    source: "Manga",
    episodes: 64,
    status: "Finished Airing",
    airing: false,
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 9.09,
    scored_by: 2100000,
    rank: 3,
    popularity: 3,
    members: 3300000,
    synopsis: "After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic state. Disregarding the alchemical taboo against human transmutation, Edward loses his left leg and Alphonse his entire physical body. Sacrificing his right arm to tether Alphonse's soul to a suit of armor, Edward sets out to become a State Alchemist and uncover the Philosopher's Stone.",
    season: "spring",
    year: 2009,
    studios: [{ mal_id: 4, name: "Bones" }],
    producers: [{ mal_id: 17, name: "Aniplex" }, { mal_id: 58, name: "Square Enix" }],
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 2, name: "Adventure" },
      { mal_id: 8, name: "Drama" },
      { mal_id: 10, name: "Fantasy" },
    ],
    streaming: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/series/GRDV0019R/fullmetal-alchemist-brotherhood" }],
  },
  {
    mal_id: 16498,
    url: "https://myanimelist.net/anime/16498/Shingeki_no_Kyojin",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/10/47347l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/10/47347.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/10/47347l.webp",
      },
    },
    trailer: {
      youtube_id: "LHtdKWJgeg4",
      url: "https://www.youtube.com/watch?v=LHtdKWJgeg4",
      embed_url: "https://www.youtube-nocookie.com/embed/LHtdKWJgeg4?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    titles: [
      { type: "Default", title: "Shingeki no Kyojin" },
      { type: "Japanese", title: "進撃の巨人" },
      { type: "English", title: "Attack on Titan" },
    ],
    title: "Shingeki no Kyojin",
    title_english: "Attack on Titan",
    title_japanese: "進撃の巨人",
    type: "TV",
    source: "Manga",
    episodes: 25,
    status: "Finished Airing",
    airing: false,
    duration: "24 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.55,
    scored_by: 2800000,
    rank: 110,
    popularity: 1,
    members: 3900000,
    synopsis: "Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide behind massive concentric walls. After a Colossal Titan breaches the outermost barrier, young Eren Yeager witnesses his mother's death and vows to eradicate every Titan by enlisting in the elite Scout Regiment.",
    season: "spring",
    year: 2013,
    studios: [{ mal_id: 858, name: "Wit Studio" }],
    producers: [{ mal_id: 10, name: "Production I.G" }, { mal_id: 144, name: "Pony Canyon" }],
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 8, name: "Drama" },
      { mal_id: 41, name: "Suspense" },
    ],
    streaming: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/series/GR751KNZY/attack-on-titan" }],
  },
  {
    mal_id: 52299,
    url: "https://myanimelist.net/anime/52299/Solo_Leveling",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1066/141444.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1066/141444l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1066/141444.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1066/141444l.webp",
      },
    },
    trailer: {
      youtube_id: "s6Y_xNtd7eI",
      url: "https://www.youtube.com/watch?v=s6Y_xNtd7eI",
      embed_url: "https://www.youtube-nocookie.com/embed/s6Y_xNtd7eI?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    titles: [
      { type: "Default", title: "Solo Leveling" },
      { type: "Japanese", title: "俺だけレベルアップな件" },
      { type: "English", title: "Solo Leveling" },
    ],
    title: "Solo Leveling",
    title_english: "Solo Leveling",
    title_japanese: "俺だけレベルアップな件",
    type: "TV",
    source: "Web manga",
    episodes: 12,
    status: "Finished Airing",
    airing: false,
    duration: "23 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.35,
    scored_by: 520000,
    rank: 210,
    popularity: 240,
    members: 810000,
    synopsis: "A decade ago, the 'Gate' opened, connecting the real world with the magic realm of monsters. Ordinary people received superhuman powers and were termed 'Hunters.' Sung Jinwoo, known as the 'Weakest Hunter of All Mankind,' is fatally injured inside a terrifying double dungeon. As he faces death, a mysterious quest window appears before him, unlocking a secret that lets him level up alone.",
    season: "winter",
    year: 2024,
    studios: [{ mal_id: 56, name: "A-1 Pictures" }],
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 2, name: "Adventure" },
      { mal_id: 10, name: "Fantasy" },
    ],
    streaming: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/series/GEXH3W253/solo-leveling" }],
  },
  {
    mal_id: 40748,
    url: "https://myanimelist.net/anime/40748/Jujutsu_Kaisen",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1171/109222.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1171/109222l.webp",
      },
    },
    trailer: {
      youtube_id: "pkKu9hLT-t8",
      url: "https://www.youtube.com/watch?v=pkKu9hLT-t8",
      embed_url: "https://www.youtube-nocookie.com/embed/pkKu9hLT-t8?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    titles: [
      { type: "Default", title: "Jujutsu Kaisen" },
      { type: "Japanese", title: "呪術廻戦" },
      { type: "English", title: "Jujutsu Kaisen" },
    ],
    title: "Jujutsu Kaisen",
    title_english: "Jujutsu Kaisen",
    title_japanese: "呪術廻戦",
    type: "TV",
    source: "Manga",
    episodes: 24,
    status: "Finished Airing",
    airing: false,
    duration: "23 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.62,
    scored_by: 1700000,
    rank: 75,
    popularity: 12,
    members: 2450000,
    synopsis: "Idly indulging in occult club activities, high schooler Yuuji Itadori spends his days visiting his bedridden grandfather. When his occult peers unseal a rotting cursed talisman, malevolent Curses emerge. To save his friends, Yuuji swallows the finger of the King of Curses, Ryomen Sukuna, dragging him into the perilous domain of Jujutsu Sorcerers.",
    season: "fall",
    year: 2020,
    studios: [{ mal_id: 569, name: "MAPPA" }],
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 10, name: "Fantasy" },
      { mal_id: 37, name: "Supernatural" },
    ],
    streaming: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/series/GRDV0019R/jujutsu-kaisen" }],
  },
  {
    mal_id: 21,
    url: "https://myanimelist.net/anime/21/One_Piece",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1244/138851.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1244/138851l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1244/138851.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1244/138851l.webp",
      },
    },
    trailer: {
      youtube_id: "MCb13lbKSiQ",
      url: "https://www.youtube.com/watch?v=MCb13lbKSiQ",
      embed_url: "https://www.youtube-nocookie.com/embed/MCb13lbKSiQ?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    titles: [
      { type: "Default", title: "One Piece" },
      { type: "Japanese", title: "ONE PIECE" },
      { type: "English", title: "One Piece" },
    ],
    title: "One Piece",
    title_english: "One Piece",
    title_japanese: "ONE PIECE",
    type: "TV",
    source: "Manga",
    episodes: 1120,
    status: "Currently Airing",
    airing: true,
    duration: "24 min per ep",
    rating: "PG-13 - Teens 13 or older",
    score: 8.73,
    scored_by: 1350000,
    rank: 45,
    popularity: 20,
    members: 2300000,
    synopsis: "Barely surviving in a barrel after passing through a terrible whirlpool at sea, carefree Monkey D. Luffy ends up aboard a pirate ship under attack. Dreaming of finding the legendary treasure 'One Piece' left by King of the Pirates Gol D. Roger, Luffy sails across the Grand Line gathering loyal crewmates.",
    season: "fall",
    year: 1999,
    studios: [{ mal_id: 18, name: "Toei Animation" }],
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 2, name: "Adventure" },
      { mal_id: 10, name: "Fantasy" },
    ],
    streaming: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece" }],
  },
  {
    mal_id: 38000,
    url: "https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba",
    images: {
      jpg: {
        image_url: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
      },
      webp: {
        image_url: "https://cdn.myanimelist.net/images/anime/1286/99889.webp",
        large_image_url: "https://cdn.myanimelist.net/images/anime/1286/99889l.webp",
      },
    },
    trailer: {
      youtube_id: "6vMuWuWlW4I",
      url: "https://www.youtube.com/watch?v=6vMuWuWlW4I",
      embed_url: "https://www.youtube-nocookie.com/embed/6vMuWuWlW4I?enablejsapi=1&wmode=opaque&autoplay=1",
    },
    titles: [
      { type: "Default", title: "Kimetsu no Yaiba" },
      { type: "Japanese", title: "鬼滅の刃" },
      { type: "English", title: "Demon Slayer: Kimetsu no Yaiba" },
    ],
    title: "Kimetsu no Yaiba",
    title_english: "Demon Slayer: Kimetsu no Yaiba",
    title_japanese: "鬼滅の刃",
    type: "TV",
    source: "Manga",
    episodes: 26,
    status: "Finished Airing",
    airing: false,
    duration: "23 min per ep",
    rating: "R - 17+ (violence & profanity)",
    score: 8.49,
    scored_by: 2200000,
    rank: 125,
    popularity: 5,
    members: 3100000,
    synopsis: "Ever since the death of his father, the burden of supporting the family has fallen upon Tanjiro Kamado. Living high on a snowy mountain, Tanjiro descends to sell charcoal. One morning, he returns home to discover his entire family slaughtered by demons, and his sister Nezuko turned into a flesh-eating creature with human emotions.",
    season: "spring",
    year: 2019,
    studios: [{ mal_id: 43, name: "ufotable" }],
    genres: [
      { mal_id: 1, name: "Action" },
      { mal_id: 10, name: "Fantasy" },
      { mal_id: 37, name: "Supernatural" },
    ],
    streaming: [{ name: "Crunchyroll", url: "https://www.crunchyroll.com/series/GY5P48XEY/demon-slayer-kimetsu-no-yaiba" }],
  },
];
